# -*- coding: utf-8 -*-
"""wwdaca3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14YlQi5l6KUBzh4TQlPgilWGy_OpioAcf
"""

import pandas as pd

df = pd.read_csv("/content/wwdac NintendoGames CLEANED.csv")
df.head()

import ast
df['genres'] = df['genres'].apply(ast.literal_eval)
df.head()

genres_encoded = df['genres'].explode().str.get_dummies().groupby(level=0).sum()

genres_encoded = genres_encoded.add_prefix('genre')

nintendo_games_encoded = pd.concat([df, genres_encoded], axis=1)

nintendo_games_encoded.head()

output_path = "/content/wwdac_NintendoGames_CLEANED_ENCODED.csv"
nintendo_games_encoded.to_csv(output_path, index=False)

